name: sickle
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - click=8.1.7
  - comm=0.2.2
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=12.4.127
  - cuda-libraries=11.6.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.4.127
  - cuda-nsight-compute=12.4.1
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.4.127
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.4.127
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.4.127
  - cuda-runtime=11.6.1
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=12.4.127
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-visual-tools=11.6.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - docker-pycreds=0.4.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - ffmpeg=4.3
  - freetype=2.12.1
  - gds-tools=1.9.1.3
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.3
  - ipython=8.18.1
  - jedi=0.19.1
  - jpeg=9e
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcufile=1.9.1.3
  - libcufile-dev=1.9.1.3
  - libcurand=10.3.5.147
  - libcurand-dev=10.3.5.147
  - libcusolver=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - nsight-compute=2024.1.1.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.2.1
  - packaging=24.0
  - parso=0.8.4
  - pathtools=0.1.2
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.1
  - platformdirs=4.2.1
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - pysocks=1.7.1
  - python=3.9.19
  - python-dateutil=2.9.0
  - python_abi=3.9
  - pytorch=1.13.0
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - tornado=6.4
  - traitlets=5.14.3
  - typing_extensions=4.9.0
  - urllib3=2.1.0
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - affine==2.4.0
      - albumentations==1.3.1
      - altair==5.3.0
      - appdirs==1.4.4
      - attrs==23.2.0
      - blinker==1.8.1
      - cachetools==5.3.3
      - click-plugins==1.1.1
      - cligj==0.7.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - fiona==1.9.6
      - fonttools==4.51.0
      - geopandas==0.12.2
      - gitdb==4.0.11
      - gitpython==3.1.43
      - imageio==2.34.1
      - importlib-resources==6.4.0
      - jinja2==3.1.3
      - joblib==1.4.0
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - networkx==3.2.1
      - opencv-python==4.5.5.64
      - opencv-python-headless==4.9.0.80
      - pandas==2.2.2
      - protobuf==4.25.3
      - pyarrow==16.0.0
      - pydeck==0.9.0
      - pyparsing==3.1.2
      - pyproj==3.6.1
      - pytz==2024.1
      - qudida==0.0.4
      - rasterio==1.3.10
      - referencing==0.35.1
      - rich==13.7.1
      - rpds-py==0.18.0
      - scikit-image==0.22.0
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.13.2
      - sentry-sdk==2.0.0
      - setproctitle==1.3.3
      - shapely==2.0.4
      - smmap==5.0.1
      - snuggs==1.4.7
      - streamlit==1.34.0
      - tenacity==8.2.3
      - threadpoolctl==3.4.0
      - tifffile==2024.4.24
      - toml==0.10.2
      - toolz==0.12.1
      - torchmetrics==0.11.4
      - torchnet==0.0.4
      - tqdm==4.64.1
      - tzdata==2024.1
      - visdom==0.2.4
      - wandb==0.13.10
      - watchdog==4.0.0
      - websocket-client==1.8.0
